FROM php:7.0-apache
MAINTAINER Inti Gabriel <inti.gabriel+github@intigabriel.de>

RUN a2enmod rewrite
ENV APACHE_RUN_USER=www-data APACHE_RUN_GROUP=www-data APACHE_LOG_DIR=/var/log/apache2 APACHE_LOCK_DIR=/var/lock/apache2 APACHE_PID_FILE=/var/run/apache2.pid

COPY apache-config.conf /etc/apache2/sites-enabled/000-default.conf
COPY apaxy/ /var/www/html/
RUN mv /var/www/html/htaccess.txt /var/www/html/.htaccess && \
mv /var/www/html/theme/htaccess.txt /var/www/html/theme/.htaccess && \
rm -f /var/www/html/index.html && \
touch /var/www/html/sample.7z  && \
touch /var/www/html/sample.bz2  && \
touch /var/www/html/sample.cab  && \
touch /var/www/html/sample.gz  && \
touch /var/www/html/sample.tar  && \
touch /var/www/html/sample.zip && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.aac  && \
touch /var/www/html/sample.aif  && \
touch /var/www/html/sample.aifc  && \
touch /var/www/html/sample.aiff  && \
touch /var/www/html/sample.ape  && \
touch /var/www/html/sample.au  && \
touch /var/www/html/sample.flac  && \
touch /var/www/html/sample.iff  && \
touch /var/www/html/sample.m4a  && \
touch /var/www/html/sample.mid  && \
touch /var/www/html/sample.mp3  && \
touch /var/www/html/sample.mpa  && \
touch /var/www/html/sample.ra  && \
touch /var/www/html/sample.wav  && \
touch /var/www/html/sample.wma  && \
touch /var/www/html/sample.f4a  && \
touch /var/www/html/sample.f4b  && \
touch /var/www/html/sample.oga  && \
touch /var/www/html/sample.ogg  && \
touch /var/www/html/sample.xm  && \
touch /var/www/html/sample.it  && \
touch /var/www/html/sample.s3m  && \
touch /var/www/html/sample.mod && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.bin  && \
touch /var/www/html/sample.hex && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.bmp && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.c && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.xlsx  && \
touch /var/www/html/sample.xlsm  && \
touch /var/www/html/sample.xltx  && \
touch /var/www/html/sample.xltm  && \
touch /var/www/html/sample.xlam  && \
touch /var/www/html/sample.xlr  && \
touch /var/www/html/sample.xls  && \
touch /var/www/html/sample.csv && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.iso && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.cpp && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.css  && \
touch /var/www/html/sample.sass  && \
touch /var/www/html/sample.scss && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.deb && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.doc  && \
touch /var/www/html/sample.docx  && \
touch /var/www/html/sample.docm  && \
touch /var/www/html/sample.dot  && \
touch /var/www/html/sample.dotx  && \
touch /var/www/html/sample.dotm  && \
touch /var/www/html/sample.log  && \
touch /var/www/html/sample.msg  && \
touch /var/www/html/sample.odt  && \
touch /var/www/html/sample.pages  && \
touch /var/www/html/sample.rtf  && \
touch /var/www/html/sample.tex  && \
touch /var/www/html/sample.wpd  && \
touch /var/www/html/sample.wps && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.svg  && \
touch /var/www/html/sample.svgz && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.ai  && \
touch /var/www/html/sample.eps && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.exe && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.gif && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.h && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.html  && \
touch /var/www/html/sample.xhtml  && \
touch /var/www/html/sample.shtml  && \
touch /var/www/html/sample.htm  && \
touch /var/www/html/sample.URL  && \
touch /var/www/html/sample.url && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.ico && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.jar && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.jpg  && \
touch /var/www/html/sample.jpeg  && \
touch /var/www/html/sample.jpe && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.js  && \
touch /var/www/html/sample.json && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.md && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.pkg  && \
touch /var/www/html/sample.dmg && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.pdf && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.php  && \
touch /var/www/html/sample.phtml && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.m3u  && \
touch /var/www/html/sample.m3u8  && \
touch /var/www/html/sample.pls  && \
touch /var/www/html/sample.pls8 && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.png && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.ps && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.psd && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.py && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.rar && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.rb && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.rpm && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.rss && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.bat  && \
touch /var/www/html/sample.cmd  && \
touch /var/www/html/sample.sh && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.sql && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.tiff  && \
touch /var/www/html/sample.tif && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.txt  && \
touch /var/www/html/sample.nfo && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.asf  && \
touch /var/www/html/sample.asx  && \
touch /var/www/html/sample.avi  && \
touch /var/www/html/sample.flv  && \
touch /var/www/html/sample.mkv  && \
touch /var/www/html/sample.mov  && \
touch /var/www/html/sample.mp4  && \
touch /var/www/html/sample.mpg  && \
touch /var/www/html/sample.rm  && \
touch /var/www/html/sample.srt  && \
touch /var/www/html/sample.swf  && \
touch /var/www/html/sample.vob  && \
touch /var/www/html/sample.wmv  && \
touch /var/www/html/sample.m4v  && \
touch /var/www/html/sample.f4v  && \
touch /var/www/html/sample.f4p  && \
touch /var/www/html/sample.ogv && \
touch /var/www/html/sample.png  && \
touch /var/www/html/sample.xml 

EXPOSE 80

CMD /usr/sbin/apache2ctl -D FOREGROUND
