FROM php:7.0-apache
MAINTAINER Inti Gabriel <inti.gabriel+github@intigabriel.de>

RUN a2enmod rewrite
ENV APACHE_RUN_USER=www-data APACHE_RUN_GROUP=www-data APACHE_LOG_DIR=/var/log/apache2 APACHE_LOCK_DIR=/var/lock/apache2 APACHE_PID_FILE=/var/run/apache2.pid

COPY apache-config.conf /etc/apache2/sites-enabled/000-default.conf
COPY apaxy/ /var/www/html/{FOLDERNAME}/
RUN mv /var/www/html/{FOLDERNAME}/htaccess.txt /var/www/html/{FOLDERNAME}/.htaccess && \
mv /var/www/html/{FOLDERNAME}/theme/htaccess.txt /var/www/html/{FOLDERNAME}/theme/.htaccess && \
rm -f /var/www/html/{FOLDERNAME}/index.html && \
touch /var/www/html/{FOLDERNAME}/sample.7z  && \
touch /var/www/html/{FOLDERNAME}/sample.bz2  && \
touch /var/www/html/{FOLDERNAME}/sample.cab  && \
touch /var/www/html/{FOLDERNAME}/sample.gz  && \
touch /var/www/html/{FOLDERNAME}/sample.tar  && \
touch /var/www/html/{FOLDERNAME}/sample.zip && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.aac  && \
touch /var/www/html/{FOLDERNAME}/sample.crx  && \
touch /var/www/html/{FOLDERNAME}/sample.aif  && \
touch /var/www/html/{FOLDERNAME}/sample.aifc  && \
touch /var/www/html/{FOLDERNAME}/sample.aiff  && \
touch /var/www/html/{FOLDERNAME}/sample.ape  && \
touch /var/www/html/{FOLDERNAME}/sample.au  && \
touch /var/www/html/{FOLDERNAME}/sample.flac  && \
touch /var/www/html/{FOLDERNAME}/sample.iff  && \
touch /var/www/html/{FOLDERNAME}/sample.m4a  && \
touch /var/www/html/{FOLDERNAME}/sample.mid  && \
touch /var/www/html/{FOLDERNAME}/sample.mp3  && \
touch /var/www/html/{FOLDERNAME}/sample.mpa  && \
touch /var/www/html/{FOLDERNAME}/sample.ra  && \
touch /var/www/html/{FOLDERNAME}/sample.wav  && \
touch /var/www/html/{FOLDERNAME}/sample.wma  && \
touch /var/www/html/{FOLDERNAME}/sample.f4a  && \
touch /var/www/html/{FOLDERNAME}/sample.f4b  && \
touch /var/www/html/{FOLDERNAME}/sample.oga  && \
touch /var/www/html/{FOLDERNAME}/sample.ogg  && \
touch /var/www/html/{FOLDERNAME}/sample.xm  && \
touch /var/www/html/{FOLDERNAME}/sample.it  && \
touch /var/www/html/{FOLDERNAME}/sample.s3m  && \
touch /var/www/html/{FOLDERNAME}/sample.mod && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.bin  && \
touch /var/www/html/{FOLDERNAME}/sample.hex && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.bmp && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.c && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.xlsx  && \
touch /var/www/html/{FOLDERNAME}/sample.xlsm  && \
touch /var/www/html/{FOLDERNAME}/sample.xltx  && \
touch /var/www/html/{FOLDERNAME}/sample.xltm  && \
touch /var/www/html/{FOLDERNAME}/sample.xlam  && \
touch /var/www/html/{FOLDERNAME}/sample.xlr  && \
touch /var/www/html/{FOLDERNAME}/sample.xls  && \
touch /var/www/html/{FOLDERNAME}/sample.csv && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.iso && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.cpp && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.css  && \
touch /var/www/html/{FOLDERNAME}/sample.sass  && \
touch /var/www/html/{FOLDERNAME}/sample.scss && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.deb && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.doc  && \
touch /var/www/html/{FOLDERNAME}/sample.docx  && \
touch /var/www/html/{FOLDERNAME}/sample.docm  && \
touch /var/www/html/{FOLDERNAME}/sample.dot  && \
touch /var/www/html/{FOLDERNAME}/sample.dotx  && \
touch /var/www/html/{FOLDERNAME}/sample.dotm  && \
touch /var/www/html/{FOLDERNAME}/sample.log  && \
touch /var/www/html/{FOLDERNAME}/sample.msg  && \
touch /var/www/html/{FOLDERNAME}/sample.odt  && \
touch /var/www/html/{FOLDERNAME}/sample.pages  && \
touch /var/www/html/{FOLDERNAME}/sample.rtf  && \
touch /var/www/html/{FOLDERNAME}/sample.tex  && \
touch /var/www/html/{FOLDERNAME}/sample.wpd  && \
touch /var/www/html/{FOLDERNAME}/sample.wps && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.svg  && \
touch /var/www/html/{FOLDERNAME}/sample.svgz && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.ai  && \
touch /var/www/html/{FOLDERNAME}/sample.eps && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.exe && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.gif && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.h && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.html  && \
touch /var/www/html/{FOLDERNAME}/sample.xhtml  && \
touch /var/www/html/{FOLDERNAME}/sample.shtml  && \
touch /var/www/html/{FOLDERNAME}/sample.htm  && \
touch /var/www/html/{FOLDERNAME}/sample.URL  && \
touch /var/www/html/{FOLDERNAME}/sample.url && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.ico && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.jar && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.jpg  && \
touch /var/www/html/{FOLDERNAME}/sample.jpeg  && \
touch /var/www/html/{FOLDERNAME}/sample.jpe && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.js  && \
touch /var/www/html/{FOLDERNAME}/sample.json && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.md && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.pkg  && \
touch /var/www/html/{FOLDERNAME}/sample.dmg && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.pdf && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.php  && \
touch /var/www/html/{FOLDERNAME}/sample.phtml && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.m3u  && \
touch /var/www/html/{FOLDERNAME}/sample.m3u8  && \
touch /var/www/html/{FOLDERNAME}/sample.pls  && \
touch /var/www/html/{FOLDERNAME}/sample.pls8 && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.png && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.ps && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.psd && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.py && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.rar && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.rb && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.rpm && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.rss && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.bat  && \
touch /var/www/html/{FOLDERNAME}/sample.cmd  && \
touch /var/www/html/{FOLDERNAME}/sample.sh && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.sql && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.tiff  && \
touch /var/www/html/{FOLDERNAME}/sample.tif && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.txt  && \
touch /var/www/html/{FOLDERNAME}/sample.nfo && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
touch /var/www/html/{FOLDERNAME}/sample.asf  && \
touch /var/www/html/{FOLDERNAME}/sample.asx  && \
touch /var/www/html/{FOLDERNAME}/sample.avi  && \
touch /var/www/html/{FOLDERNAME}/sample.flv  && \
touch /var/www/html/{FOLDERNAME}/sample.mkv  && \
touch /var/www/html/{FOLDERNAME}/sample.mov  && \
touch /var/www/html/{FOLDERNAME}/sample.mp4  && \
touch /var/www/html/{FOLDERNAME}/sample.mpg  && \
touch /var/www/html/{FOLDERNAME}/sample.rm  && \
touch /var/www/html/{FOLDERNAME}/sample.srt  && \
touch /var/www/html/{FOLDERNAME}/sample.swf  && \
touch /var/www/html/{FOLDERNAME}/sample.vob  && \
touch /var/www/html/{FOLDERNAME}/sample.wmv  && \
touch /var/www/html/{FOLDERNAME}/sample.m4v  && \
touch /var/www/html/{FOLDERNAME}/sample.f4v  && \
touch /var/www/html/{FOLDERNAME}/sample.f4p  && \
touch /var/www/html/{FOLDERNAME}/sample.ogv && \
touch /var/www/html/{FOLDERNAME}/sample.png  && \
mkdir /var/www/html/{FOLDERNAME}/SampleFolder  && \
touch /var/www/html/{FOLDERNAME}/SampleFolder/sample.xml 

EXPOSE 80

CMD /usr/sbin/apache2ctl -D FOREGROUND
